version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  info_file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    mode: a
  debug_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: logs/debug.log
    mode: a
  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: standard
    filename: logs/error.log
    mode: a
loggers:
  src:
    level: DEBUG
    handlers: [console, info_file, debug_file, error_file]
    propagate: False
root:
  level: INFO
  handlers: [console, info_file, debug_file, error_file]
