# File: config/logging_config.yaml

version: 1
formatters:
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
loggers:
  '':
    level: DEBUG
    handlers: [console, file]
    propagate: True
