version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: logs/debug.log
    mode: a

  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    mode: a

  warning_file_handler:
    class: logging.FileHandler
    level: WARNING
    formatter: standard
    filename: logs/warning.log
    mode: a

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: standard
    filename: logs/error.log
    mode: a

  critical_file_handler:
    class: logging.FileHandler
    level: CRITICAL
    formatter: standard
    filename: logs/critical.log
    mode: a

root:
  level: DEBUG
  handlers:
    - console_handler
    - debug_file_handler
    - info_file_handler
    - warning_file_handler
    - error_file_handler
    - critical_file_handler

# Optionally, you can define other loggers here
loggers:
  # Example of a custom logger
  my_module_logger:
    level: INFO
    handlers:
      - console_handler
    propagate: no
